name: Mirroring

on: [push]

jobs:
  to_foundries:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: foundriesio/mirror-action@master
        with:
          REMOTE: "https://source.foundries.io/factories/tutorial/containers.git"
          GIT_ACCESS_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
          PUSH_ALL_REFS: "false"
          DEBUG: "true"
